trigger:
  branches:
    include:
    - master
pool:
  vmImage: 'windows-latest'
variables:
- name: buildConfiguration
  value: 'Release'
stages:
- stage: Build
  displayName: Build Application
  jobs:
  - job: BuildJob
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '9.x'
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration Release'
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
    - task: ecdc45f6-832d-4ad9-b52b-ee49e94659be@1
      inputs:
        path: $(Build.ArtifactStagingDirectory)
        artifactName: drop
- stage: DeployQA
  displayName: Deploy to QA
  dependsOn:
  - Build
  jobs:
  - deployment: QADeploy
    environment:
      name: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - task: 30f35852-3f7e-4c0c-9a88-e127b4f97211@1
            inputs:
              alias: current
              artifact: drop
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'myservice-connection'
              appType: 'webApp'
              appName: 'azuredevopappakash'
              deployToSlotOrASE: true
              resourceGroupName: 'VisualStudioOnline-000D36FE59E949D7A0C0F01F40CCCACF'
              slotName: 'staging-qa'
              package: '$(Pipeline.Workspace)/drop/**/*.zip'

